import {
  RiFile3Line,
  RiFileCodeLine,
  RiFileDownloadLine,
  RiFileExcel2Line,
  RiFilePdf2Line,
  RiFileTextLine,
  RiImageLine,
  RiFolderZipLine,
} from "react-icons/ri";

import { downloadFile } from "../../services/fileService";

import "./FileCard.scss";


function iconFor(name = "") {
  const ext = String(name)
    .split(".")
    .pop()
    ?.toLowerCase();

  if (ext === "pdf") return <RiFilePdf2Line />;

  if (
    ["js", "jsx", "ts", "tsx", "py", "java", "cpp", "c", "html", "css", "scss", "sql"].includes(ext)
  ) {
    return <RiFileCodeLine />;
  }

  if (["xlsx", "xls", "csv"].includes(ext)) {
    return <RiFileExcel2Line />;
  }

  if (["png", "jpg", "jpeg", "webp", "gif", "bmp"].includes(ext)) {
    return <RiImageLine />;
  }

  if (ext === "zip") return <RiFolderZipLine />;

  if (["txt", "md", "docx", "json", "xml", "yml", "yaml"].includes(ext)) {
    return <RiFileTextLine />;
  }

  return <RiFile3Line />;
}


function formatSize(bytes = 0) {
  const size = Number(bytes) || 0;

  if (size < 1024) return `${size} B`;
  if (size < 1024 * 1024) return `${(size / 1024).toFixed(1)} KB`;

  return `${(size / (1024 * 1024)).toFixed(1)} MB`;
}


export default function FileCard({
  file,
  generated = false,
  compact = false,
}) {
  if (!file || typeof file !== "object") {
    return null;
  }

  const safeFile = {
    ...file,
    id: file.id || "",
    filename: file.filename || file.name || "Attached file",
    size: file.size || 0,
  };

  const handleDownload = async () => {
    try {
      await downloadFile(safeFile);
    } catch (error) {
      console.error("Download failed:", error);
    }
  };

  return (
    <div
      className={`file-card ${generated ? "is-generated" : ""} ${
        compact ? "is-compact" : ""
      }`}
    >
      <div className="file-card__icon">
        {iconFor(safeFile.filename)}
      </div>

      <div className="file-card__info">
        <strong title={safeFile.filename}>
          {safeFile.filename}
        </strong>

        <span>
          {generated
            ? "Generated by Aether"
            : formatSize(safeFile.size)}
        </span>
      </div>

      {safeFile.download_url && (
        <button
          className="file-card__download"
          type="button"
          onClick={handleDownload}
          aria-label={`Download ${safeFile.filename}`}
          title={`Download ${safeFile.filename}`}
        >
          <RiFileDownloadLine />
        </button>
      )}
    </div>
  );
}
